name: Build assets icons

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build:lib
      - name: Save build
        uses: actions/upload-artifact@v4
        with:
          name: remanxng-build
          path: dist/remanxng
          retention-days: 1

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dist/remanxng
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: remanxng-build
          path: dist/remanxng
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.APP_TOKEN}}
